<?xml version="1.0" encoding="utf-8"?><Database Name="DB_PLANT_BCS_KPD" Class="DB_Plant_BCSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.14.101.101\shpol;Initial Catalog=DB_PLANT_BCS_KPD;Persist Security Info=True;User ID=sqlservices" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_PLANT_BCS_KPDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_M_ROLE" Member="TBL_M_ROLEs">
    <Type Name="TBL_M_ROLE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_M_USER" Member="TBL_M_USERs">
    <Type Name="TBL_M_USER">
      <Column Name="ID_Role" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_R_MENU" Member="TBL_R_MENUs">
    <Type Name="TBL_R_MENU">
      <Column Name="ID_Menu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name_Menu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sub_Menu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Icon_Menu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Link_Menu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Akses" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_R_SUB_MENU" Member="TBL_R_SUB_MENUs">
    <Type Name="TBL_R_SUB_MENU">
      <Column Name="ID_Sub_Menu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Menu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sub_Menu_Description" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Link_Sub_Menu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Akses" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_M_AKSES" Member="VW_M_AKSEs">
    <Type Name="VW_M_AKSE">
      <Column Name="ID_Menu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name_Menu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID_Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KARYAWAN_ALL" Member="VW_KARYAWAN_ALLs">
    <Type Name="VW_KARYAWAN_ALL">
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POSITION_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POS_TITLE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="WORK_LOC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMP_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GENDER_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BIRTH_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HIRE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SERVICE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TERMINATION_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SUPERIOR_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POSITION_START_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GOLONGAN" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ACTIVE_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_M_SOURCE" Member="TBL_M_SOURCEs">
    <Type Name="TBL_M_SOURCE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SOURCE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_User" Member="VW_Users">
    <Type Name="VW_User">
      <Column Name="ID_Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KARYAWAN_PLANT" Member="VW_KARYAWAN_PLANTs">
    <Type Name="VW_KARYAWAN_PLANT">
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POSITION_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POS_TITLE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="WORK_LOC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMP_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GENDER_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BIRTH_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HIRE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SERVICE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TERMINATION_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SUPERIOR_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POSITION_START_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GOLONGAN" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ACTIVE_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KARYAWAN_PLANT_N_MCH" Member="VW_KARYAWAN_PLANT_N_MCHes">
    <Type Name="VW_KARYAWAN_PLANT_N_MCH">
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POSITION_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POS_TITLE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="WORK_LOC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMP_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GENDER_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BIRTH_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HIRE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SERVICE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TERMINATION_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SUPERIOR_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POSITION_START_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GOLONGAN" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ACTIVE_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_T_RECOMMENDED_REPAIR" Member="TBL_T_RECOMMENDED_REPAIRs">
    <Type Name="TBL_T_RECOMMENDED_REPAIR">
      <Column Name="REPAIR_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NO_BACKLOG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROBLEM_DESC" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ACTIVITY_REPAIR" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_MENU" Member="VW_MENUs">
    <Type Name="VW_MENU">
      <Column Name="ID_Menu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name_Menu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID_Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="IS_ALLOW" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_M_AKSES" Member="TBL_M_AKSEs">
    <Type Name="TBL_M_AKSE">
      <Column Name="ID_Menu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Role" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IS_ALLOW" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_H_BACKLOG_WO_WR" Member="TBL_H_BACKLOG_WO_WRs">
    <Type Name="TBL_H_BACKLOG_WO_WR">
      <Column Name="NO_BACKLOG" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WO_NO" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IREQ_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_T_BACKLOG" Member="TBL_T_BACKLOGs">
    <Type Name="TBL_T_BACKLOG">
      <Column Name="NO_BACKLOG" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EQP_NUMBER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="COMP_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EGI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BACKLOG_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INSPECTON_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="INSPECTOR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SOURCE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WORK_GROUP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STD_JOB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NRP_GL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ORIGINATOR_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PLAN_REPAIR_DATE_1" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PLAN_REPAIR_DATE_2" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MANPOWER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOUR_EST" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="POSISI_BACKLOG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REMARKS" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="INSTALL_DATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_M_JOBSITE" Member="VW_M_JOBSITEs">
    <Type Name="VW_M_JOBSITE">
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="Char(18) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_ACC_SUPPLY" Member="VW_R_ACC_SUPPLies">
    <Type Name="VW_R_ACC_SUPPLY">
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="IREQ_ITEM" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="IREQ_NO" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="LAST_ACQ_DATE" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="STOCK_CODE" Type="System.String" DbType="Char(9) NOT NULL" CanBeNull="false" />
      <Column Name="WHOUSE_ID" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_COMP_CODE" Member="VW_R_COMP_CODEs">
    <Type Name="VW_R_COMP_CODE">
      <Column Name="COMP_CODE" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
      <Column Name="COMP_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_COMPLETE_CODE" Member="VW_R_COMPLETE_CODEs">
    <Type Name="VW_R_COMPLETE_CODE">
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="WORK_ORDER" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="COMPLETED_CODE" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="COMP_CODE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="JOB_DUR_DATE" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="JOB_DUR_START" Type="System.String" DbType="Char(4)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_EQ_NUMBER" Member="VW_R_EQ_NUMBERs">
    <Type Name="VW_R_EQ_NUMBER">
      <Column Name="EQUIP_NO" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="EQUIP_GRP_ID" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_LOCATION_ON_STOCK" Member="VW_R_LOCATION_ON_STOCKs">
    <Type Name="VW_R_LOCATION_ON_STOCK">
      <Column Name="TABLE_CODE" Type="System.String" DbType="Char(18) NOT NULL" CanBeNull="false" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="WH" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="TABLE_DESC" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_MENU" Member="VW_R_MENUs">
    <Type Name="VW_R_MENU">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ID_Menu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name_Menu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sub_Menu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Icon_Menu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Link_Menu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_PART_READY_DATE_MASTER" Member="VW_R_PART_READY_DATE_MASTERs">
    <Type Name="VW_R_PART_READY_DATE_MASTER">
      <Column Name="DISTRICT" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NO_BACKLOG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EQP_NUMBER" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STOCK_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QTY_PART" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ACT_ONSITE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BATCHING_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_STD_JOB" Member="VW_R_STD_JOBs">
    <Type Name="VW_R_STD_JOB">
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="STD_JOB_NO" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="STD_JOB_DESC" Type="System.String" DbType="Char(40) NOT NULL" CanBeNull="false" />
      <Column Name="WORK_GROUP" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_T_PART_BACKLOG" Member="VW_T_PART_BACKLOGs">
    <Type Name="VW_T_PART_BACKLOG">
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="PART_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STOCK_CODE" Type="System.String" DbType="Char(9)" CanBeNull="true" />
      <Column Name="UOM" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="STK_DESC" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PART_CLASS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PART_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NO_BACKLOG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FIG_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INDEX_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QTY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ETA_SUPPLY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LOCATION_ON_STOCK" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AVAILABLE_STOCK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ACT_ONSITE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IREQ_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ACCTUAL_SUPPLY_DATE" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_T_PART_REQUEST" Member="VW_T_PART_REQUESTs">
    <Type Name="VW_T_PART_REQUEST">
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="PART_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STOCK_CODE" Type="System.String" DbType="Char(9)" CanBeNull="true" />
      <Column Name="UOM" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="STK_DESC" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PART_CLASS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PART_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NO_BACKLOG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FIG_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INDEX_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QTY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ETA_SUPPLY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LOCATION_ON_STOCK" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AVAILABLE_STOCK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EQP_NUMBER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="COMP_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EGI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BACKLOG_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INSPECTON_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SOURCE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WORK_GROUP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STD_JOB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NRP_GL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ORIGINATOR_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PLAN_REPAIR_DATE_1" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="POSISI_BACKLOG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_T_RECOMMENDED_PART" Member="TBL_T_RECOMMENDED_PARTs">
    <Type Name="TBL_T_RECOMMENDED_PART">
      <Column Name="PART_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NO_BACKLOG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PART_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FIG_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INDEX_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QTY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ETA_SUPPLY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LOCATION_ON_STOCK" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AVAILABLE_STOCK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MNEMONIC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_PART_MSF170" Member="VW_R_PART_MSF170s">
    <Type Name="VW_R_PART_MSF170">
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="PART_NO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MNEMONIC" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="STOCK_CODE" Type="System.String" DbType="Char(9) NOT NULL" CanBeNull="false" />
      <Column Name="UOM" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="STK_DESC" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PART_CLASS" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="PREF_PART_IND" Type="System.String" DbType="Char(2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_STOCK_CODE" Member="VW_R_STOCK_CODEs">
    <Type Name="VW_R_STOCK_CODE">
      <Column Name="STOCK_CODE" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="PART_NO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="MNEMONIC" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PREF_PART_IND" Type="System.String" DbType="Char(2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_WH_STOCK_CODE" Member="VW_WH_STOCK_CODEs">
    <Type Name="VW_WH_STOCK_CODE">
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="STOCK_CODE" Type="System.String" DbType="Char(9) NOT NULL" CanBeNull="false" />
      <Column Name="WHOUSE_ID" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_T_BACKLOG" Member="VW_T_BACKLOGs">
    <Type Name="VW_T_BACKLOG">
      <Column Name="NO_BACKLOG" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EQP_NUMBER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="COMP_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="COMP_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EGI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BACKLOG_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INSPECTON_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="INSPECTOR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INSPECTOR_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SOURCE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WORK_GROUP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STD_JOB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NRP_GL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NRP_GL_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ORIGINATOR_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ORIGINATOR_ID_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PLAN_REPAIR_DATE_1" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PLAN_REPAIR_DATE_2" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MANPOWER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOUR_EST" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="POSISI_BACKLOG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REMARKS" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="WO_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IREQ_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INSTALL_DATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KARYAWAN_PLANT_HAULING" Member="VW_KARYAWAN_PLANT_HAULINGs">
    <Type Name="VW_KARYAWAN_PLANT_HAULING">
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(61)" CanBeNull="true" />
      <Column Name="POSITION_ID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="POS_TITLE" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WORK_LOC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMP_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GENDER_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BIRTH_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HIRE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SERVICE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TERMINATION_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SUPERIOR_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POSITION_START_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GOLONGAN" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ACTIVE_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KARYAWAN_PLANT_TRACK" Member="VW_KARYAWAN_PLANT_TRACKs">
    <Type Name="VW_KARYAWAN_PLANT_TRACK">
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(61)" CanBeNull="true" />
      <Column Name="POSITION_ID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="POS_TITLE" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WORK_LOC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMP_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GENDER_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BIRTH_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HIRE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SERVICE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TERMINATION_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SUPERIOR_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POSITION_START_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GOLONGAN" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ACTIVE_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KARYAWAN_PLANT_WHEEL" Member="VW_KARYAWAN_PLANT_WHEELs">
    <Type Name="VW_KARYAWAN_PLANT_WHEEL">
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(61)" CanBeNull="true" />
      <Column Name="POSITION_ID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="POS_TITLE" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WORK_LOC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMP_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GENDER_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STAFF_CATEG_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BIRTH_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HIRE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SERVICE_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TERMINATION_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS_HIRE_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SUPERIOR_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="POSITION_START_DATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GOLONGAN" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_CODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_DESC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ACTIVE_STATUS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_EQ_NUMBER_HAULING" Member="VW_R_EQ_NUMBER_HAULINGs">
    <Type Name="VW_R_EQ_NUMBER_HAULING">
      <Column Name="EQUIP_NO" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="EQUIP_GRP_ID" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VW_R_EQ_NUMBER_TRACK_WHEEL" Member="VW_R_EQ_NUMBER_TRACK_WHEELs">
    <Type Name="VW_R_EQ_NUMBER_TRACK_WHEEL">
      <Column Name="EQUIP_NO" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="EQUIP_GRP_ID" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="DSTRCT_CODE" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.cusp_NotifBacklogCancel" Method="cusp_NotifBacklogCancel">
    <Parameter Name="NO_BACKLOG" Parameter="nO_BACKLOG" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
</Database>